class SolvingError(Exception):
    '''
    Custom Error to be able to catch this error seperatly.
    '''
    pass